### ISSUE TITLE
yarn new view not working

### ISSUE THREAD

**Issue by ctwoodwa** [frandiox/vue-graphql-enterprise-boilerplate#3]
trying the following command
yarn new view --name forgotpassword

results in:
yarn run v1.6.0
$ hygen new view --name forgotpassword
(node:24224) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Path must be a string. Received undefined
(node:24224) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 0.55s.

Am I missing a npm package?  are you able to create new views following the instructions?

**Comment by frandiox** [comment]
@ctwoodwa I can run commands like mentioned [in the docs](https://github.com/frandiox/vue-enterprise-boilerplate/blob/d64d4a047836bf3c08e3ee1f458110bf85e0e750/docs/development.md#generators) (without `--name` param).

By the way, are you using this repo's `master` branch for components in folders? Or are you using `apollo` or `appsync` branches for GraphQL stuff?
