### ISSUE TITLE
Auth0 error

### ISSUE THREAD

**Issue by bitmatix** [frandiox/vue-graphql-enterprise-boilerplate#31]
Signup via Auth0 works but if I try to login I always get an error:

`Error: Not authorized. Could not get signing key: Unable to find a signing key that matches...`

Any ideas?

**Comment by frandiox** [comment]
Hi! You also need to set up env variables for the server in `server/.env`. I think you might be missing `AUTH0_DOMAIN` there.

**Comment by bitmatix** [comment]
@frandiox Hi, I think I've setup everything correctly. `VUE_APP_AUTH0_CLIENT_ID` and `VUE_APP_AUTH0_DOMAIN` are configured.

**Comment by frandiox** [comment]
To be clear, there are 3 AUTH0 env variables:

- `VUE_APP_AUTH0_CLIENT_ID` in `project/.env`
- `VUE_APP_AUTH0_DOMAIN` in `project/.env`
- `AUTH0_DOMAIN` in `project/server/.env`

The last 2 need to have the same value. The signing key is necessary for authenticating JWT (tokens) and for that the `AUTH0_DOMAIN` variable in the server needs to be set up.
