### ISSUE TITLE
Different lint depending on how you use it.

### ISSUE THREAD

**Issue by marceloavf** [frandiox/vue-graphql-enterprise-boilerplate#41]
Hey!

I'm noticing some difference when using `yarn lint` compared to `editor.formatOnSave`, I've read the troubleshooting about another extension could be breaking this one, but after a clean install of `vscode`, `yarn` and `node` and only installing recommended extensions by the workspace the problems continues.

**Example:**

In this code snippet running `yarn lint` we have this exactly format, but when using `editor.formatOnSave` it goes different, looking at the log seems that it's not respecting Prettier.

`yarn lint` 
https://github.com/frandiox/vue-graphql-enterprise-boilerplate/blob/1a9a296f86315b105c49b23c54d14f50f98c14d0/src/router/views/home/index.vue#L35-L42

`editor.formatOnSave`
```vue
<img class="logo" src="@assets/images/logo.png" alt="Logo">
<h2>Recent Posts</h2>
<PostList v-if="!isLoadingRecentPosts && recentPosts" :posts="recentPosts" show-author/>
```

Thank you!

---

**Extra info:**

When testing out the same code snippet with `chrisvfritz` repository the problem disappear.

**Comment by frandiox** [comment]
@marceloavf Thanks for reporting!

I've noticed this issue after cherry-picking some commits from Chris' repo. Probably he made some changes in the linter and I forgot to add some commit/code :/

**Comment by marceloavf** [comment]
No problem @frandiox 

I'm trying to compare configurations files with his ones. If I find it I'll let you know.
