### ISSUE TITLE
How to mock $apollo in Vue tests

### ISSUE THREAD

**Issue by Michelemassari** [frandiox/vue-graphql-enterprise-boilerplate#43]
Hello. I'm trying to write jest test for my Vue components but every apollo query is met with an error like this

```
TypeError: Cannot read property 'queries' of undefined

      110 |   computed: {
      111 |     isLoadingChannels() {
    > 112 |       return this.$apollo.queries.channels.loading || false
          | ^
      113 |     },
      114 |   },

```

Is there any way I can mock the $apollo object?

I've found [some tutorials](https://github.com/Akryum/vue-apollo/issues/244) ([another one](https://dev.to/n_tepluhina/testing-vue-apollo-components-with-jest-3gj3)) but don't know how to apply it to this boilerplate. Any help would be greatly appreciated.

**Comment by frandiox** [comment]
@Michelemassari Hi! I've found that mocking Apollo is quite complex and there are little docs out there for this. Luckily, I've already spent some time in a similar project and managed to do it. I will update this template soon and maybe write some blog post or something.

If you just want to mock the `$apollo` object you can pass mocks to [vue-test-utils](https://vue-test-utils.vuejs.org/api/#mount) or add a global mock in `test/setup.js` ([like this](https://vue-test-utils.vuejs.org/api/#config)).

For anything more complex than that (like properly mocking queries or mutations) I will need some more time to update this boilerplate.

**Comment by Michelemassari** [comment]
Hey @frandiox. Thanks for the super quick reply!

Could you please give me a quick example of the `test/setup.js` mock?
I would just need something very simple for now for my tests to pass and enable my CI deploy.
I would rather not disable all the tests as others are written and needed.

I've tried 
`
returnOptions.mocks.$apollo = {}
`
with no luck

**Comment by frandiox** [comment]
@Michelemassari I have something like this for vue-i18n: `vueTestUtils.config.mocks.$t = key => key`. I guess `vueTestUtils.config.mocks.$apollo = { ... }` could work, but not 100% sure.
